version: '3.9'
services:
  couchdb:
    image: couchdb
    container_name: budgeting-app-couchdb
    env_file:
      - .env
    volumes:
      - "./data:/opt/couchdb/data"
    ports:
      - "${PORT:-5984}:5984"
